# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/metadata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .options import fieldoptions_pb2 as shared_dot_options_dot_fieldoptions__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from .enums import environment_pb2 as shared_dot_enums_dot_environment__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='shared/metadata.proto',
  package='travix.contracts.shared',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15shared/metadata.proto\x12\x17travix.contracts.shared\x1a!shared/options/fieldoptions.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eshared/enums/environment.proto\"\xd9\x03\n\x08MetaData\x12>\n\tunique_id\x18\x01 \x01(\tB+\x82\xb5\x18\'Uniquely identifies the event instance.\x12\x34\n\nsession_id\x18\x02 \x01(\tB \x82\xb5\x18\x1cIdentifies the user session.\x12K\n\nrequest_id\x18\x03 \x01(\tB7\x82\xb5\x18\x33Supply Hub specific identifier, unique per request.\x12\x14\n\x0cmessage_type\x18\x04 \x01(\t\x12Y\n\rutc_timestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB&\x82\xb5\x18\"Time when this event is generated.\x12\x18\n\x10\x62usiness_process\x18\x06 \x01(\t\x12\x7f\n\x0b\x65nvironment\x18\x08 \x01(\x0e\x32\x36.travix.contracts.shared.enums.environment.EnvironmentB2\x82\xb5\x18.The environment where this event is generated.b\x06proto3')
  ,
  dependencies=[shared_dot_options_dot_fieldoptions__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,shared_dot_enums_dot_environment__pb2.DESCRIPTOR,])




_METADATA = _descriptor.Descriptor(
  name='MetaData',
  full_name='travix.contracts.shared.MetaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unique_id', full_name='travix.contracts.shared.MetaData.unique_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\'Uniquely identifies the event instance.'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='travix.contracts.shared.MetaData.session_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\034Identifies the user session.'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='travix.contracts.shared.MetaData.request_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\0303Supply Hub specific identifier, unique per request.'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_type', full_name='travix.contracts.shared.MetaData.message_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='utc_timestamp', full_name='travix.contracts.shared.MetaData.utc_timestamp', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\"Time when this event is generated.'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='business_process', full_name='travix.contracts.shared.MetaData.business_process', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='environment', full_name='travix.contracts.shared.MetaData.environment', index=6,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030.The environment where this event is generated.'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=624,
)

_METADATA.fields_by_name['utc_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_METADATA.fields_by_name['environment'].enum_type = shared_dot_enums_dot_environment__pb2._ENVIRONMENT
DESCRIPTOR.message_types_by_name['MetaData'] = _METADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetaData = _reflection.GeneratedProtocolMessageType('MetaData', (_message.Message,), dict(
  DESCRIPTOR = _METADATA,
  __module__ = 'shared.metadata_pb2'
  # @@protoc_insertion_point(class_scope:travix.contracts.shared.MetaData)
  ))
_sym_db.RegisterMessage(MetaData)


_METADATA.fields_by_name['unique_id']._options = None
_METADATA.fields_by_name['session_id']._options = None
_METADATA.fields_by_name['request_id']._options = None
_METADATA.fields_by_name['utc_timestamp']._options = None
_METADATA.fields_by_name['environment']._options = None
# @@protoc_insertion_point(module_scope)
