# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/options/messageoptions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='shared/options/messageoptions.proto',
  package='travix.contracts.shared.options.messageptions',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n#shared/options/messageoptions.proto\x12-travix.contracts.shared.options.messageptions\x1a google/protobuf/descriptor.proto:6\n\x0b\x64\x65scription\x12\x1f.google.protobuf.MessageOptions\x18\xd0\x86\x03 \x01(\t:3\n\x08gdpr_pii\x12\x1f.google.protobuf.MessageOptions\x18\xd1\x86\x03 \x01(\x08\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


DESCRIPTION_FIELD_NUMBER = 50000
description = _descriptor.FieldDescriptor(
  name='description', full_name='travix.contracts.shared.options.messageptions.description', index=0,
  number=50000, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
GDPR_PII_FIELD_NUMBER = 50001
gdpr_pii = _descriptor.FieldDescriptor(
  name='gdpr_pii', full_name='travix.contracts.shared.options.messageptions.gdpr_pii', index=1,
  number=50001, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)

DESCRIPTOR.extensions_by_name['description'] = description
DESCRIPTOR.extensions_by_name['gdpr_pii'] = gdpr_pii
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(description)
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(gdpr_pii)

# @@protoc_insertion_point(module_scope)
