# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/enums/journeytype.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shared/enums/journeytype.proto',
  package='travix.contracts.shared.enums.journeytype',
  syntax='proto3',
  serialized_options=_b('\n\035travix.contracts.shared.enums'),
  serialized_pb=_b('\n\x1eshared/enums/journeytype.proto\x12)travix.contracts.shared.enums.journeytype*X\n\x0bJourneyType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06RETURN\x10\x01\x12\x0b\n\x07ONE_WAY\x10\x02\x12\x0c\n\x08OPEN_JAW\x10\x03\x12\x15\n\x11MULTI_DESTINATION\x10\x04\x42\x1f\n\x1dtravix.contracts.shared.enumsb\x06proto3')
)

_JOURNEYTYPE = _descriptor.EnumDescriptor(
  name='JourneyType',
  full_name='travix.contracts.shared.enums.journeytype.JourneyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RETURN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONE_WAY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPEN_JAW', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTI_DESTINATION', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=77,
  serialized_end=165,
)
_sym_db.RegisterEnumDescriptor(_JOURNEYTYPE)

JourneyType = enum_type_wrapper.EnumTypeWrapper(_JOURNEYTYPE)
UNKNOWN = 0
RETURN = 1
ONE_WAY = 2
OPEN_JAW = 3
MULTI_DESTINATION = 4


DESCRIPTOR.enum_types_by_name['JourneyType'] = _JOURNEYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
