# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/enums/searchtype.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shared/enums/searchtype.proto',
  package='travix.contracts.shared.enums.searchtype',
  syntax='proto3',
  serialized_options=_b('\n\035travix.contracts.shared.enums'),
  serialized_pb=_b('\n\x1dshared/enums/searchtype.proto\x12(travix.contracts.shared.enums.searchtype*;\n\nSearchType\x12\x0c\n\x08STANDARD\x10\x00\x12\x11\n\rSPECIAL_OFFER\x10\x01\x12\x0c\n\x08\x43\x41LENDAR\x10\x02\x42\x1f\n\x1dtravix.contracts.shared.enumsb\x06proto3')
)

_SEARCHTYPE = _descriptor.EnumDescriptor(
  name='SearchType',
  full_name='travix.contracts.shared.enums.searchtype.SearchType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STANDARD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPECIAL_OFFER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALENDAR', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=75,
  serialized_end=134,
)
_sym_db.RegisterEnumDescriptor(_SEARCHTYPE)

SearchType = enum_type_wrapper.EnumTypeWrapper(_SEARCHTYPE)
STANDARD = 0
SPECIAL_OFFER = 1
CALENDAR = 2


DESCRIPTOR.enum_types_by_name['SearchType'] = _SEARCHTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
