# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/enums/shopenhancement.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shared/enums/shopenhancement.proto',
  package='travix.contracts.shared.enums.shopenhancement',
  syntax='proto3',
  serialized_options=_b('\n\035travix.contracts.shared.enums'),
  serialized_pb=_b('\n\"shared/enums/shopenhancement.proto\x12-travix.contracts.shared.enums.shopenhancement*3\n\x0fShopEnhancement\x12\n\n\x06NORMAL\x10\x00\x12\x14\n\x10\x43OMBINED_ONE_WAY\x10\x01\x42\x1f\n\x1dtravix.contracts.shared.enumsb\x06proto3')
)

_SHOPENHANCEMENT = _descriptor.EnumDescriptor(
  name='ShopEnhancement',
  full_name='travix.contracts.shared.enums.shopenhancement.ShopEnhancement',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMBINED_ONE_WAY', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=85,
  serialized_end=136,
)
_sym_db.RegisterEnumDescriptor(_SHOPENHANCEMENT)

ShopEnhancement = enum_type_wrapper.EnumTypeWrapper(_SHOPENHANCEMENT)
NORMAL = 0
COMBINED_ONE_WAY = 1


DESCRIPTOR.enum_types_by_name['ShopEnhancement'] = _SHOPENHANCEMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
